version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/seb43_main_033/main
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/seb43_main_033/main
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
  - location: deploy.sh
    timeout: 60
    runas: ubuntu
