import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-white h-28 drop-shadow-lg w-screen z-1 top-0 fixed"></header>
        <div className="flex flex-row">
          <aside className="p-4 border-r-2 border-solid border-stone-300 w-60 h-screen"></aside>
          <div className="flex-grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
