import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/Link"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Link href="/worker">worker</Link>{children}</body>
    </html>
  )
}
